default_config:

logger:
  default: info
  logs:
    custom_components.waste_collection_schedule: debug

# Change these config to your needs
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Rsa
        mm_frm_ort_sel: Alfter
        mm_frm_str_sel: Ahrweg (105-Ende/94-Ende)

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
